### PR TITLE
BearerToken support embedio v2

### PR DESCRIPTION
**Pull request by bufferUnderrun**
hi,

Can you merge this patch to support embedio v2 by the BearerToken Module.
Also, can you update the nugget package ?

Thanks.

### CODE REVIEW

**Comment by geoperez** [comment]
Already have an open PR (#15), affecting all the modules. Let me review mine first, then check differences with yours.

**Review by geoperez — APPROVED** [review]

**Comment by geoperez** [comment]
We have the same changes, I will close your PR. Give me a minute to publish the nuget. Thank you.

**Comment by geoperez** [comment]
The new nuget was published.

**Comment by bufferUnderrun** [comment]
Sorry, i did not check for an existing PR before posting.
Thanks for the nuget package.

**Pull request closed without merging**
